### ISSUE TITLE
cart-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [anyudenko/Angular2plus#4]
private sub: Subscription;
private sub2: Subscription;
private sub3: Subscription;

Вместо этих трех свойств можно использовать одно. Я вам показывал такой пример в формах. Создать одно своство, а потом использовать метод this.sub.add(anotherSub) + this.sub.unsibscribe - отпишеться от всех подписок.

**Comment by anyudenko** [comment]
Исправлено в ветке Task9
